name: Check if issue or PR has a milestone
on:
  issues:
    types: [opened, milestoned, demilestoned]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node_version: 10.x

      - name: Install Yarn
        run: npm install -g yarn

      - name: Cache Node Modules
        id: cache-node-modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-node_modules

      - name: Yarn Install
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        # frozen-lockfile will make the build fail if the lockfile is not there
        run: yarn install --frozen-lockfile

      - name: Validate PR Labels
        run: |
          yarn run danger ci \
            --dangerfile dangerfiles/milestone.ts
            --id milestone
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
