name: Experiment with context and expressions
on:
  push:
  # I was hoping that adding or removing a milestone from a PR
  # would trigger this event, but it doesn't
  # milestone: types: [edited]
  issues:
    types: [milestoned, demilestoned]

jobs:
  echo:
    runs-on: ubuntu-16.04
    steps:
      # This will run on every push
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      # This should run only if the action was milestone or demilestoned.
      - name: Dump Action (only for milestones)
        if: (github.event.action == 'milestoned') || (github.event.action) == 'demilestoned'
        env:
          ACTION: ${{ github.event.action }}
          #RESULT: ${{ toJson(github.event.action) == "milestoned" || toJson(github.event.action) == "demilestoned" }}
          #RESULT: ${{ toJson(github.event)["action"] }}
          RESULT: ${{ (github.event.action == 'milestoned') || (github.event.action) == 'demilestoned' }}
        run: |
          echo "action: $ACTION"
          echo "action is acceptable: $RESULT"
      - name: ✌️
        if: (github.event.action == 'milestoned') || (github.event.action) == 'demilestoned' && github.event.pull_request != ''
        run: |
          echo "✌️"
