name: Experiment with context and expressions
on:
  # I was hoping that adding or removing a milestone from a PR
  # would trigger this event, but it doesn't
  # milestone: types: [edited]
  issues:
    types: [milestoned, demilestoned]

jobs:
  echo:
    runs-on: ubuntu-16.04
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump Action
        env:
          ACTION: ${{ toJson(github.event.action) }}
          RESULT: ${{ toJson(github.event.action) == "milestoned" || toJson(github.event.action) == "demilestoned" }}
        run: |
          echo "$ACTION"
          echo "$RESULT"
